### ISSUE TITLE
React-ify the Deck!

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-deck#105]
# WIP

## Current stack
- The current JavaScript framework uses AngularJS
  - Relies heavily on two-way binding within it
- Optimistic frontend
  - Surfaces some errors to the user. (@ramirezg can talk more about his work with the routes and services error handling)
  - Otherwise, fails silently.
- Bootstrap 3
- Frontend Unit Tests
  - @ramirezg can talk more about this system
  - Not covering all edge cases
- Retry system (very much well needed)
  - The CloudFoundry API, that the Go Backend talks to, will timeout so we have the frontend tell the backend retry on certain URLs (@ramirezg  can tell more about which URLs)
  - Need to somehow show an error if even the retry system fails

#### [Angular-ladda](https://github.com/remotty/angular-ladda)
- Used for having bootstrap buttons with spinners to indicate progress

#### [ngSanitize](https://docs.angularjs.org/api/ngSanitize)
-@ramirezg fill in about this

#### [angular-bootstrap-confirm aka mwl.confirm](https://github.com/mattlewis92/angular-bootstrap-confirm)
- Used for confirmation dialogs. Usually used for destructive / highly impactful actions.
- Not sure if the ATDD framework would like this.
![image](https://cloud.githubusercontent.com/assets/7788930/9796012/d97d65ac-57c1-11e5-89be-2fe8f172d7d2.png)

#### [angular-toggle-switch](https://github.com/cgarvis/angular-toggle-switch)
- Used for toggling roles of users.
- Not sure if the ATDD framework would like this.
![image](https://cloud.githubusercontent.com/assets/7788930/9795993/bfb65caa-57c1-11e5-9156-d256642a6166.png)

#### HappyFox Chat
- Used for customers to talk to us about problems
- Cooked into the frontend. (Hard for someone else to fork the project)

#### Statuspage.io
- Used to indicate the overall status of all of the components.
- Used as AngularJS directive in the header.
- ~~BUG: Doesn't refresh when we go from page to page.~~ (Fixed by Pull [107](https://github.com/18F/cf-deck/pull/107))
- Cooked into the frontend. (Hard for someone else to fork the project)

## New stack
- React
- Gov't Pattern Library
 
# WIP

**Comment by msecret** [comment]
## React Flux refactor
### Current items we should consider fixing
* __App controller methods too big, even pass too many params__
* __Heavily nested and confusing async behavior__
  * __Load org function seems to have strange async behavior that could cause race conditions__
  * Many functions have async nesting
* __Most code is at a page level rather then modular component level__
* Front end performance isn't great due to having to load some many files
* App isn't accessible without JS
* __Difficult to render app on the backend__
* __Seemingly limited ability to share data structures (no models or stores)__
* __Scope in controllers seems very global__
* __Limited ability to run on thing before another or time async events__
* __No build process to allow for minification, etc.__
* __Ctrl and service files are very large__
* Tests have confusing file names

__Bolded items__ are things that would be fixed by the react/flux refactor

### Pros and cons of frameworks
Information can be found here: https://github.com/18F/frontend/blob/18f-pages-staging/pages/recommended/mvv_frameworks.md. The basics though are this:

#### Angular cons
* Everything has to be down "angular way", learn angular more then JS or front end
* Is harder to reverse decisions. It's such a large framework that touches so many things, it's hard to pull angular out.
* Stuck using angular plugin system
* New 2.0 upgrade path leaves 1.x apps behind.

#### React Pros over Angular
* Is just the view part of FE framework
* Can re-render without worrying about performance
* More es6 ready
* Important to teach the 18f team

#### React cons
* JSX can be confusing as it has different rules from HTML and doesn't always provide the best errors
  * Can be mitigated by different compile options and not using JSX in certain circumstances
* Still stuck in react plugin system, but only for view components.

#### Flux pros
* Allows for plain JS objects for most code, limited framework code allowing for more simple and shareable interfaces.
* Very easy to add non-REST services like web sockets
* Unidirectional data flow
  * Ensures data and event flow won't get confusing
  * Clean way of sharing events or data structures between multiple components.
* Uses events structure and eliminates nested callbacks
* Requires little 3rd party software

#### Flux cons
* More verbose in terms of files and directory structure
* May take more time to initially figure out structure of specific app.

### Estimate of conversion to react+ flux
* 2 - 5 : global/build process restructure
* 2 - 5 : global/confirm modal
* 1 - 2 : global/chat
* 1 - 2 : global/status
* 3 - 5 : global/pager (not req)
* 2 - 4 : global/retry (not req)
* 2 : sidebar/orgs list
* 1 - 2 : login
* 4 - 5 : sidebar/org nav
  * 1 - 2 : dropdown with nav
  * 3 : change name and links on org change
* 1 - 2 : sidebar/quota usage
* 1 - 2 : org/spaces
* 1 - 2 : org/marketplace
* 4 - 7 : marketplace/plans
  * 2 - 3 : list
  * 2 - 4 : create service instance
* 8 - 15 : org/space
  * 2 - 4 : double nav
  * 1 - 3 : apps
  * 2 - 3 : service instances
  * 2 - 3 : user management, current
  * 1 - 2 : user management, all
* 9 - 18 : app
  * 3 - 6 : log & events
  * 1 - 3 : basic info
  * 1 - 2 : start/stop
  * 4 - 7 : routes
* 5 - 9 : space/user
  * 3 - 4 : info
  * 2 - 5 : toggle button
* 4 - 6 : space/users
  * 3 - 4 : list
  * 1 - 2 : add user

**Comment by msecret** [comment]
I have a question or two on this:

- As we develop the react fork, would we want to keep it as a separate branch until it's completed, or would we want to try and merge in as we go along? Merging in as we go along could actually be much more complicated as it would require us to restructure the current app.
- Would I be the sole developer working on this?
- Are there any current features that shouldn't be built as they are but we're planning to change?

**Comment by dlapiduz** [comment]
@msecret:
> As we develop the react fork, would we want to keep it as a separate branch until it's completed, or would we want to try and merge in as we go along? Merging in as we go along could actually be much more complicated as it would require us to restructure the current app.

Branch is fine

> Would I be the sole developer working on this?

Highly likely you are going to be the only one full time but you will have the support of the whole team as you go.

> Are there any current features that shouldn't be built as they are but we're planning to change?

Not really, the UI is pretty basic as it is.

**Comment by dlapiduz** [comment]
I'd say lets just move on with it and get it done as soon as we can...
