### ISSUE TITLE
Org user management is in the wrong place

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#116]
@dlapiduz and I were talking a bit about the outcome of [this story](https://trello.com/c/P1vQN4w9/220-ui-manage-user-permissions).

Org-level user management is accessed by first drilling down into a space. This is really misleading and confusing information architecture!
![example](https://cloud.18f.gov/img/manage-space-users.png)

Some suggestions for cleaning this up:

- Move the tab for managing org-level perms to the org view, alongside the list of spaces, as simply "User Management"... Let the IA make it clear that it's at the org-level. 
- The pictured area would then only concern managing users for that space, so the extra "[current|all]" row of tabs could be removed and make this much easier to understand. 
- The "inherited" users from the org level could be shown in the space-specific list in a read-only form. This would keep that a comprehensive list of people with access to the space.

**Comment by ramirezg** [comment]
So this is something that we should absolutely redesign because it's confusing.

Just to clarify: Org user management is handled at the Org level. The `All CF Org Users` tab that you see above is for adding users that are already in the Org to that space. 

Ideally there would be one table that lists all the Org users, but also flags users that have permission in that space.

**Comment by mogul** [comment]
> Just to clarify: Org user management is handled at the Org level. The All CF Org Users tab that you see above is for adding users that are already in the Org to that space.

Ohhhhhhh! I totally misunderstood that tab on the right, then. And maybe I don't have permissions to see the user management tab at the org level?
