### ISSUE TITLE
Pre-launch: Add logout button to UI

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#179]
In order for a user to change which account they're logged into, there should be a logout button in the UI.

**Comment by jeremiak** [comment]
So what if instead of "Deck" we put "Login" (or "Logout") in the nav bar on the deck project? This would:

0. Make the nav link more useful since its pretty clear nobody knows what "Deck" means
0. Put the link on the far right side of the navigation
0. Provide an obvious place to put a "Logout" link

**Comment by msecret** [comment]
Its funny, @vz3 was just talking about this. @vz3, @thisisdano, @juliaelman what do y'all think?

**Comment by thisisdano** [comment]
Sounds simple and logical.

**Comment by jeremiak** [comment]
I did a really simple take in #296, would appreciate your opinions @vz3 @thisisdano @juliaelman and @msecret
