### ISSUE TITLE
Add CSS code linting

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#183]
In order for developers to write code in a consistent style, there should be a decided upon coding style guide with linting tools and configuration.

Files that are currently failing linting should be added to a lintignore file that will ensure the linter doesn't error for them.

Acceptance criteria
- [ ] A developer should be able to find what CSS style guide is the standard in the CONTRIBUTING document.
- [x] The automated tests should not pass if a file is not linted.
- [x] A developer should be able to see specific output on why their linting failed, including file and file number.
- [x] A developer should be able to add linting to a file by removing the file from a lint ignore file.

**Comment by jeremiak** [comment]
Adding to the backlog because we're looking for a linter that isn't ruby based

**Comment by jeremiak** [comment]
We have a few options for JS based linters.

[`sass-lint`](https://github.com/sasstools/sass-lint) looks pretty compelling, especially since it has a built in [`scss-lint` config converter](http://sasstools.github.io/make-sass-lint-config/) which could aid in the transition.

There is also a PostCSS-based tool (which doesn't support sass) called [`stylelint`](https://github.com/stylelint/stylelint) that we could use as a CSS linter but might not be the best option since it:

0. does not support Sass
0. diverges from the [18F front end guild guidelines](https://pages.18f.gov/frontend/css-coding-styleguide/) since the configs are not compatible.

**Comment by msecret** [comment]
We're going to go with `stylelint`. It does support sass, and we're working on a config for 18F by adding some postcss plugins.

**Comment by msecret** [comment]
Sorry, wrote that before reading your answer.

Why isn't styelint compatible with scss?

**Comment by msecret** [comment]
Ended up picking this up because it coincided with a task I had to do for the front end guild and because it will be nice to have with more people working on the cg-style codebase.

**Comment by jeremiak** [comment]
I'm going to evaluate the acceptance criteria against the style guide repo because of 18f/cg-style#83

**Comment by jeremiak** [comment]
@msecret this looks almost done. The last criteria is:
> A developer should be able to find what CSS style guide is the standard in the CONTRIBUTING document.

**Comment by msecret** [comment]
Good call, will add now.

**Comment by msecret** [comment]
It's actually here: https://github.com/18F/cg-style/blob/master/documentation/frontend_standards.md

**Comment by jeremiak** [comment]
We don't have a `CONTRIBUTING` doc in 18f/cg-style (so that's bad acceptance criteria) but the style guide/linting information is there.
