### ISSUE TITLE
Add view of routes on the app page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#283]
In order for developers to know the URLs of their app there should be a list of routes on the app page

Acceptance criteria
- [ ] For each route in the list, there should be the following information: `host`, `domain`

**Comment by msecret** [comment]
Design:

API: https://apidocs.cloudfoundry.org/237/apps/list_all_routes_for_the_app.html

```js

RouteStore
  on routeActions.ROUTES_RESV:
    this.merge('guid', action.routes);

```

**Comment by msecret** [comment]
@jeremiak @jcscottiii would appreciate feedback on design.

**Comment by jeremiak** [comment]
I like the idea of having two different methods that we mix into a larger entity. Our code will stay maintainable if we have a more lego block approach where we can mix and match functions to add functionality instead of having to write some from scratch. I also am not sure we'll ever need a DomainStore because then we'd constantly have to be doing join like actions in the app code.

I think we can still use the merge function, but we might have to shape the API responses differently. For example, let's say this is in our RouteStore:

```
{
  guid,
  app_guid,
  ...
}
```

And our data returned from the domain request looks something like:

```
{
    "guid": "fakeDomainGuid",
    "url": "/v2/private_domains/fakeDomainGuid",
    "created_at": "2015-02-18T06:31:48Z",
    "updated_at": "2015-10-12T16:36:36Z",
    "name": "18f.gov",
    "owning_organization_guid": "fakeOrgGuid",
    "owning_organization_url": "/v2/organizations/fakeOrgGuid",
    "shared_organizations_url": "/v2/private_domains/fakeDomainGuid/shared_organizations"
}
```

From which we could generate a JS object that has this shape:

```
{
  domain_guid:  "fakeDomainGuid",
  domain: {
    name: "18f.gov
  }
}
```

Then we can still use `.merge('domain_guid', ...)` to get the domain on each route in the RouteStore. I would prefer this approach over adding another method to the BaseStore because I think the method API might start to be complicated with two key strings. But we can easily create the desired data structure in code, and use our standard functions which are easy to reason about and are familiar since they're used in almost every store.

Thoughts?

**Comment by msecret** [comment]
Yea I like that idea too, and the more I think about it the less I want another method on BaseStore or make the merge method more complicated. So in this case, we'd take the domain object and change or add the `domain_guid` key which will equal the `guid` key?

**Comment by jeremiak** [comment]
Ya, exactly. Then it is explicit in the function how the new object is being created before the merge so it makes it a bit easier to understand IMHO.

I'm fine with more BaseStore methods (as I just [added `.delete()`](https://github.com/18F/cg-deck/commit/193245fdf385b320b986efd3d31c1dad7ff75662)) but I think we should keep those methods pretty simple and wait until we see the need for it arise in a few of the store implementations.
