### ISSUE TITLE
Delete action buttons should have a confirmation

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-deck#307]
The user should be prompted to confirm their intent when they click on a delete action. For example, when a user clicks "Delete service instance" they should get a message similar to:

> Are you sure you want to delete this service instance? This action is permanent and takes effect immediately.

Acceptance criteria:
- [x] A visually distinct box should appear adjacent to the delete button.
- [x] The delete button should be inactive and display as inactive while the confirmation box is active.
- [x] There should be a `confirm delete` button that's red.
- [x] There should be a `cancel` button that's blank/white state.

Post-MVP
- [ ] The confirmation should slide in or fade pop in.
- [ ] The confirmation box should be a modal over the text.

**Comment by msecret** [comment]
Where should this message occur in the UI? There currently isn't a modal pattern, and I'm apprehensive to create a new pattern right now. Can the UI appear below the delete button?

**Comment by msecret** [comment]
Quick mockup for what the new UI could look like:

![ui_mock-delete_instance](https://cloud.githubusercontent.com/assets/1701077/15839009/dad53070-2bf5-11e6-92bd-bc89a836a687.png)

**Comment by msecret** [comment]
With more detailed message:

![ui_mock-delete_instance-v2](https://cloud.githubusercontent.com/assets/1701077/15839459/4886d432-2bf8-11e6-8f4f-79df9549c39e.png)

**Comment by thisisdano** [comment]
If we wanted a modal pattern, one could look like this:
![confirm-delete-pattern](https://cloud.githubusercontent.com/assets/11464021/15839360/cb692f4a-2bf7-11e6-8d2c-78a6a5c568ee.png)

- It's definitely best if the confirmation doesn't bump text. It's acceptable if it does, but it's jumpy.
- I'd like to see the original delete button go into a disabled state while the confirm is in progress.
- It'd also be nice to see a cancel button that was neither the standard action button nor the red warning button.
- I think the actions should be explicit in the button text rather than explanatory text. "confirm delete" and "cancel" seem ok.

Alternately, the confirm action could slide in (or fade-pop, or simply replace):
![confirm-delete-pattern-2](https://cloud.githubusercontent.com/assets/11464021/15839687/98028758-2bf9-11e6-81da-9ccf661d15f2.png)

Eh, maybe a little strange....

But — if it must insert — I think the disabled state, the button copy, and the cancel style could be implemented.

**Comment by msecret** [comment]
K, I'll write some acceptance criteria based on that, although I think I'll focus on a quick MVP

**Comment by dlapiduz** [comment]
The sliding one is interesting but I wonder if it complicates things too much.
