### ISSUE TITLE
There should be helpful copy on the initial deck page

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-deck#309]
The current homepage for the deck (once you have logged in) has very little copy and doesn't give the user much useful information for navigating and using the deck.

When an authenticated user comes to the deck, they should see some useful copy to provide them with necessary context for using the application.

Screenshot of initial dashboard view:
![The initial view of the application as it stands now](https://s3.amazonaws.com/f.cl.ly/items/0M382u0i2V250Q314647/Screen%20Shot%202016-06-03%20at%201.39.33%20PM.png?v=2eab17a5)

**Comment by brittag** [comment]
I made [a Google Drawing](https://docs.google.com/drawings/d/1a9WD7gXMyfj8qEr95NUMffUwz7S5qkJ8IYOhhw8AFuU/edit) with a draft of homepage copy. I'd be interested in corrections to any misleading phrasing!

Basic user stories I have in mind for this homepage:

* In order to learn about cloud.gov as a newcomer who doesn't want to exhaustively read all the documentation as my first step, I want to jump into the Dashboard and see _just enough_ explanation to help me get started and make something happen.
* In order to use cloud.gov effectively as a person who isn't excited about always living in the command line, and who only occasionally needs to manage something in my cloud.gov applications, I need the Dashboard to give me friendly in-context reminders of key concepts so that I don't feel overwhelmed every time I need to look at it.

Acceptance criteria I have in mind:

- [ ] The Dashboard has friendly, useful, and accurate content on its homepage.
