### ISSUE TITLE
Improve UI pattern for nested tables

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#314]
In order for user of the deck to understand the marketplace interface, there should be some slight design improvements made to nested tables.

Acceptance criteria
- [x] Nested tables should be have more natural spacing.

**Comment by thisisdano** [comment]
See https://github.com/18F/cg-style/pull/79 and https://github.com/18F/cg-deck/pull/319

This change address tables both nested and not. Whether the change is slight, I leave it up to judgment of the beholder.

- - -

This change addresses the usability of tables, but does not address whether a table is the correct solution for a particular display, nor does it explicitly address the kind of data displayed or its arrangement in the template. In general, this is a triage solution that tries to improve usability but does not claim to be the best display solution.

**Goals**
- To reduce atomization of individual tabular data
  - removing the border from each individual cell, replacing it with border simply on the top and bottom (encouraging a row read)
  - reducing the padding of each cell, keeping all the columnar data closer together (encouraging a column read).
- To improve hierarchy of nested data (tricky because there's no "canonical" role that a nested table plays)
  - increase distinction between nested table and containing table
  - increase connection between nested table and related containing data
- Improve button fit on tabular data
  - reduced button height in tables to fit better into rows and pack tighter

**Known Issues**
- Changes are all in stylesheets, targeting nested tables with `td table`; the best solution would use classes to name nested tables explicitly and avoid nested selectors. Not all nested tables need necessarily use the "card" style; it could be assigned explicitly with a class.
- Similarly, the compressed button style used in the tables could be assigned with a class, rather than using a contextual style, `table button`
- Using stylemaps on development builds could speed up development by helping any dev easily find and edit rules spread over multiple stylesheets.
- I aligned action buttons right with a hacky solution, targeting `td [label="Actions"]`. Perhaps there's a more explicit class we can use to align both the actions button and the actions column hed text right. (Right now the button is aligned right, but the hed is aligned left)
  - It would also be better if the buttons in the action column had no right margin, so they'd align exactly to the right edge of the table
- The styling DOES NOT play well with mobile. This is a triage, non-mobile solution only.

**Possible future improvements**
- I'd prefer to have a heavy line over rows that "begin" new data sections (i.e. those that contain a new row of data in the primary table and contain a nested table themselves, like subsequent rows of primary service info), but this is impossible to accurately target only with styles
- Some columns in the service instance table are redundant ("Free") or confusing ("Description")
- Individual column widths should be explicitly set in repeating tables (or nested tables) to improve table-table comparison and scanning. As is, the column width changes from table to table, depending on each table's specific data. Maybe use width-classes to set percentage-width columns.
- timecode should be formatted to something human-readable (and is arguably not necessary in service description data)
- The service instance name could be classed in such a way to make it more prominent (like, bold)

**Old:**
<img width="392" alt="screen shot 2016-06-07 at 7 46 49 am" src="https://cloud.githubusercontent.com/assets/11464021/15862397/63718d8c-2c84-11e6-9e33-1cce82fa6997.png">

**New:**
<img width="385" alt="screen shot 2016-06-07 at 7 32 06 am" src="https://cloud.githubusercontent.com/assets/11464021/15862405/6dfc528c-2c84-11e6-9138-d1787d622a1e.png">

**Comment by vz3** [comment]
Consider eliminating the "Free" column and changing $0.00 monthly to "Free" when it makes sense.
