### ISSUE TITLE
Communication plan for deck refactor launch

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#333]
I'm keeping this open-ended right now as I still want to discuss what we want to accomplish here. Generally though, we'll want to inform users when the deck launches as their UI will change, some functionality will be missing and some functionality will have changed.

Additionally, I think we'll want to communicate the deck to the cloud foundry community at some point. One of the goals of the deck codebase is for it to be usable and configurable by the cloud foundry community. I'd prefer to announce to the community some time after launch, as there's some additional work we might want to do to improve the open source aspects of the deck, and ensure it's easy to configure by an outside contributor. This story should likely end up focusing on just the deck userbase communicate, and we can split up the cloud foundry community communication to another story.

**Comment by brittag** [comment]
Here's a potential way to break this down into specific tasks for communicating these changes. There's some overlap here with the [checklist I drafted for GovCloud announcements](https://github.com/18F/cg-atlas/issues/59#issuecomment-223161891), since both are thinking about how to communicate product changes, although that one is different since it requires the user to take action.

To prepare for about a week ahead of time:
- [ ] Post a notification that there will be an update to the Deck on x date (as an all-channel message in the Slack support channel, and as a note posted at the top of the current Deck), as part of a general good practice of reducing the chances of people feeling unpleasant surprise/confusion on launch days. Include that it'll be an alpha and that we'll be taking feedback and answering questions.

To prepare for the day of the update:
- [ ] Write a not-too-long but helpful explanation: List what's different (what's improved, what's changed, what's missing). Explain why we changed it, what we're planning to work on next, and how to give feedback and opinions to help us prioritize changes.
- [ ] To help us incrementally systematize how we communicate with customers about product changes, decide ahead of time how we'll announce this to people and format the content for those ways (even just making a list of "email, cloud.gov update post, #cloud-gov-support announcement").
- [ ] Update any docs that also need to communicate these changes.

When we feel like announcing to the broader Cloud Foundry community, these seem like reasonable steps based on a tiny bit of looking around at how CF people talk to each other (but it would be good to get some perspective on that from an actual community participant):

- [ ] Write an 18F blog post.
- [ ] [Post to the cf-dev mailing list](http://cf-dev.70369.x6.nabble.com/).
- [ ] Ask to get our 18F cloud.gov blog tag integrated into the [CF blog aggregator](https://www.cloudfoundry.org/community/planet/).
- [ ] Write an 18F tweet and ask to be retweeted on the [CF Twitter](https://twitter.com/cloudfoundry).

**Comment by msecret** [comment]
@brittag we'll likely determine on Mon 6/20 when we will want to launch the deck. I think we can assign due dates to things then.

**Comment by brittag** [comment]
Progress so far- 

Here's the [Google Doc where I've been drafting these things](https://docs.google.com/document/d/1Qo7MBsQrP5uYm4gWVKbVdQ-ByooIg2tAWOn-8ZRxPWA/edit#).

I have PRs for the [current-Deck week-ahead update note](https://github.com/18F/cg-deck/pull/399) and the [day-of cloud.gov update post](https://github.com/18F/cg-landing/pull/78).

I did a quick check of docs.cloud.gov and I didn't immediately see any docs that need to be updated for this switchover - the docs reference CLI commands and logs.cloud.gov. (A future task might be to *add* explanations to the docs for using the Dashboard for some tasks.)

**Comment by brittag** [comment]
Revised plan:

*Next week on switchover day:*

- [ ] Put the new Dashboard on dashboard.cloud.gov (including a note at the top explaining the change and linking to the post).
- [ ] Update the site's console.cloud.gov links to go to dashboard.cloud.gov instead.
- [ ] Update the site's "Deck" links to say "Dashboard" instead.
- [ ] Publish an update post that includes "the Dashboard is now updated; the old Deck will stick around for a week".
- [ ] Put a note on top of console.cloud.gov explaining "Go to dashboard.cloud.gov for the new version. This version is going away after a week. Let us know if you’re concerned about that."
- [ ] Write an all-channel message in the Slack support channel notifying people of this change.
- [ ] Redirect https://github.com/18F/cg-deck to https://github.com/18F/cg-dashboard for consistent branding, and update the readme to reflect the name.

*A week after switchover day:"
- [ ] Redirect console.cloud.gov to dashboard.cloud.gov
- [ ] Remove update note from the top of dashboard.cloud.gov

**Comment by msecret** [comment]
Thought of a new task:

- [ ] Update 18f/cg-uaa to redirect to dashboard.cloud.gov rather then console.cloud.gov

**Comment by jeremiak** [comment]
I found another spot on [the documentation site](https://docs.cloud.gov/ops/repos/) where "console" needs to be updated.

**Comment by brittag** [comment]
Filed https://github.com/18F/cg-deck/issues/485 to take lingering tasks from this issue and put them into a correctly-named fresh issue.
