### ISSUE TITLE
Label when you're on a space page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#384]
In order for the deck users to know what space their on, there should be the space name in the content section.

Acceptance criteria
- [x] There should be the space name in the header of the content section.

**Comment by thisisdano** [comment]
So, the main-content hed should show the space name rather than "Space"

**Comment by thisisdano** [comment]
Something like this:

<img width="583" alt="screen shot 2016-06-20 at 12 54 24 pm" src="https://cloud.githubusercontent.com/assets/11464021/16208271/28187d2e-36e6-11e6-9891-b1689116d27d.png">

**Comment by thisisdano** [comment]
A follow-up to this issue is that Orgs should also be labelled clearly. Currently, their hed looks like `[space_name] spaces` and it would be clearer is it just showed the space name, similar to the proposal for spaces, and then "Spaces" was more of a table hed. For instance:

<img width="581" alt="screen shot 2016-06-20 at 12 43 01 pm" src="https://cloud.githubusercontent.com/assets/11464021/16208330/7ba0331a-36e6-11e6-92c3-41b7a8fbbbd0.png">

**Comment by jeremiak** [comment]
@thisisdano would it be better to label the header as something like "Space: testSpace01" or should it just be "testSpace01"?

**Comment by thisisdano** [comment]
I *think* it'll be clear enough (for now) with the name of the space only.
